import type { Project } from "../types";
import themeCss from "../styles/theme.css?raw";
import appCss from "../styles/app.css?raw";
import { interactionCssVars } from "./interactionVars";

/**
 * Produces a single, dependency-free .html file that reproduces the exact
 * viewer experience — fidelity to the source image, hover/selection with
 * multi-area/spotlight blocks, group connectors (line + traveling dot +
 * arrival ring), idle pulsing badges, keyboard focus parity, the sliding
 * left/right panel with "Explorer aussi" links, and every tunable value from
 * the Style panel — for any project, without needing this React app, a
 * build step, or a server. Open it directly in a browser, or drop it
 * anywhere static files are served.
 */
export function buildStandaloneHtml(project: Project): string {
  const fontHref =
    "https://fonts.googleapis.com/css2?family=" +
    encodeURIComponent(project.theme.fontDisplay) +
    ":wght@400;600;700&family=" +
    encodeURIComponent(project.theme.fontMono) +
    ":wght@400;700&display=swap";

  const dataJson = JSON.stringify(project).replace(/</g, "\\u003c");

  const vars = interactionCssVars(project.theme.interaction);
  const varsCss = Object.entries(vars)
    .map(([k, v]) => `${k}:${v}`)
    .join(";");

  return `<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(project.name)}</title>
<link rel="stylesheet" href="${fontHref}" />
<style>
${themeCss}
${appCss}
body { overflow: hidden; }
</style>
</head>
<body>
<div class="dy-app" style="${varsCss}">
  <header class="dy-topbar">
    <h1 class="dy-font-display">${escapeHtml(project.name)}</h1>
  </header>
  <main class="dy-viewer-main" id="dy-root"></main>
</div>
<script id="dy-project-data" type="application/json">${dataJson}</script>
<script>${RUNTIME_JS}</script>
</body>
</html>
`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] as string));
}

/**
 * Vanilla-JS runtime, string-concatenated on purpose (no template literals)
 * so it can be embedded inside an outer template literal without any
 * backtick/${} escaping headaches.
 */
const RUNTIME_JS = [
  "(function () {",
  "  var SVG_NS = 'http://www.w3.org/2000/svg';",
  "  var project = JSON.parse(document.getElementById('dy-project-data').textContent);",
  "  var interaction = project.theme.interaction;",
  "  var root = document.getElementById('dy-root');",
  "  var byId = {};",
  "  project.hotspots.forEach(function (hs) { byId[hs.id] = hs; });",
  "  var groupById = {};",
  "  project.groups.forEach(function (g) { groupById[g.id] = g; });",
  "  var sorted = project.hotspots.slice().sort(function (a, b) { return a.order - b.order; });",
  "  var selectedId = null;",
  "  var renderedPanelId = null;",
  "  var hoverId = null;",
  "",
  "  function h(tag, attrs, children) {",
  "    var e = document.createElement(tag);",
  "    if (attrs) for (var k in attrs) { if (k === 'class') e.className = attrs[k]; else if (k === 'style') e.setAttribute('style', attrs[k]); else e.setAttribute(k, attrs[k]); }",
  "    (children || []).forEach(function (c) { if (typeof c === 'string') e.appendChild(document.createTextNode(c)); else if (c) e.appendChild(c); });",
  "    return e;",
  "  }",
  "  function s(tag, attrs) {",
  "    var e = document.createElementNS(SVG_NS, tag);",
  "    if (attrs) for (var k in attrs) e.setAttribute(k, attrs[k]);",
  "    return e;",
  "  }",
  "  function shapePoints(shape) {",
  "    if (shape.kind === 'rect') {",
  "      return [[shape.x, shape.y], [shape.x + shape.w, shape.y], [shape.x + shape.w, shape.y + shape.h], [shape.x, shape.y + shape.h]];",
  "    }",
  "    return shape.points.map(function (p) { return [p.x, p.y]; });",
  "  }",
  "  function pointsAttr(pts) { return pts.map(function (p) { return p[0] + ',' + p[1]; }).join(' '); }",
  "  function boundsOf(shapes) {",
  "    var xs = [], ys = [];",
  "    shapes.forEach(function (shape) { shapePoints(shape).forEach(function (p) { xs.push(p[0]); ys.push(p[1]); }); });",
  "    var x1 = Math.min.apply(null, xs), y1 = Math.min.apply(null, ys);",
  "    var x2 = Math.max.apply(null, xs), y2 = Math.max.apply(null, ys);",
  "    return { kind: 'rect', x: x1, y: y1, w: x2 - x1, h: y2 - y1 };",
  "  }",
  "  function effectiveSpotlight(hs) { return hs.spotlightShape || boundsOf(hs.areas); }",
  "  function connectorPathD(from, to, curved) {",
  "    if (!curved) return 'M ' + from.x + ' ' + from.y + ' L ' + to.x + ' ' + to.y;",
  "    var mx = (from.x + to.x) / 2, my = (from.y + to.y) / 2;",
  "    var dx = to.x - from.x, dy = to.y - from.y;",
  "    var dist = Math.sqrt(dx * dx + dy * dy) || 1;",
  "    var nx = -dy / dist, ny = dx / dist;",
  "    var bend = dist * 0.18;",
  "    var cx = mx + nx * bend, cy = my + ny * bend;",
  "    return 'M ' + from.x + ' ' + from.y + ' Q ' + cx + ' ' + cy + ' ' + to.x + ' ' + to.y;",
  "  }",
  "  function effectiveConnector(hs) {",
  "    if (Object.prototype.hasOwnProperty.call(hs, 'connector')) return hs.connector;",
  "    var g = groupById[hs.groupId];",
  "    return (g && g.connector) || null;",
  "  }",
  "  function effectiveHotspotStyle(hs) {",
  "    var o = hs.style || {};",
  "    function pick(key) { return o[key] !== undefined ? o[key] : interaction[key]; }",
  "    return {",
  "      showOutline: o.showOutline !== false,",
  "      dashPattern: pick('dashPattern'),",
  "      hoverTintOpacity: pick('hoverTintOpacity'),",
  "      selectionStrokeWidth: pick('selectionStrokeWidth'),",
  "      spotlightCornerRadius: pick('spotlightCornerRadius'),",
  "      pulseEnabled: pick('pulseEnabled'),",
  "      pulseMinRadius: pick('pulseMinRadius'),",
  "      pulseMaxRadius: pick('pulseMaxRadius'),",
  "      pulseSpeedMs: pick('pulseSpeedMs'),",
  "    };",
  "  }",
  "  var styles = {};",
  "  project.hotspots.forEach(function (hs) { styles[hs.id] = effectiveHotspotStyle(hs); });",
  "",
  "  var stageCol = h('div', { class: 'dy-stage-col' });",
  "  if (project.groups.length) {",
  "    var legend = h('div', { class: 'dy-legend' });",
  "    project.groups.forEach(function (g) {",
  "      var first = sorted.filter(function (hs) { return hs.groupId === g.id; })[0];",
  "      var dot = h('span', { class: 'dy-legend-dot', style: 'background:' + g.color });",
  "      var btn = h('button', {}, [dot, g.label]);",
  "      btn.addEventListener('click', function () { if (first) select(first.id); });",
  "      legend.appendChild(btn);",
  "    });",
  "    stageCol.appendChild(legend);",
  "  }",
  "",
  "  var stage = h('div', { class: 'dy-stage' });",
  "  var stageBox = h('div', { class: 'dy-stage-box', style: 'aspect-ratio:' + project.image.width + '/' + project.image.height });",
  "  var img = h('img', { class: 'dy-stage-img', src: project.image.src, alt: project.image.alt, draggable: 'false' });",
  "  var svg = s('svg', { class: 'dy-stage-svg', viewBox: '0 0 100 100', preserveAspectRatio: 'none' });",
  "  var bg = s('rect', { x: 0, y: 0, width: 100, height: 100, fill: 'transparent' });",
  "  svg.appendChild(bg);",
  "  bg.addEventListener('click', function () { select(null); });",
  "",
  "  function spotlightEl(shape, color, es) {",
  "    var el;",
  "    if (shape.kind === 'rect') {",
  "      el = s('rect', { x: shape.x, y: shape.y, width: shape.w, height: shape.h, rx: es.spotlightCornerRadius, ry: es.spotlightCornerRadius });",
  "    } else {",
  "      el = s('polygon', { points: pointsAttr(shapePoints(shape)) });",
  "    }",
  "    el.setAttribute('class', 'dy-hotspot');",
  "    el.style.setProperty('--hs-color', color);",
  "    el.style.setProperty('--dy-hover-opacity', es.hoverTintOpacity);",
  "    el.style.setProperty('--dy-dash', es.dashPattern);",
  "    el.style.setProperty('--dy-selection-stroke', es.selectionStrokeWidth);",
  "    if (!es.showOutline) el.style.strokeOpacity = 0;",
  "    return el;",
  "  }",
  "",
  "  var spotlights = {};",
  "  project.hotspots.forEach(function (hs) {",
  "    var el = spotlightEl(effectiveSpotlight(hs), hs.color, styles[hs.id]);",
  "    spotlights[hs.id] = el;",
  "    svg.appendChild(el);",
  "  });",
  "",
  "  var arrivalSpotlight = null; // rebuilt on demand for the selected hotspot's connector.toShape",
  "",
  "  var hitGroups = {};",
  "  var pulses = {};",
  "  project.hotspots.forEach(function (hs) {",
  "    var g = s('g', {});",
  "    hs.areas.forEach(function (area) {",
  "      var p = s('polygon', { points: pointsAttr(shapePoints(area)), class: 'dy-hotspot-hit', tabindex: '0' });",
  "      p.addEventListener('mouseenter', function () { hoverId = hs.id; render(); });",
  "      p.addEventListener('mouseleave', function () { hoverId = null; render(); });",
  "      if (interaction.focusFollowsHover) {",
  "        p.addEventListener('focus', function () { hoverId = hs.id; render(); });",
  "        p.addEventListener('blur', function () { hoverId = null; render(); });",
  "      }",
  "      p.addEventListener('click', function (e) { e.stopPropagation(); select(hs.id); });",
  "      g.appendChild(p);",
  "    });",
  "    var pulse = s('circle', { cx: hs.anchor.x, cy: hs.anchor.y, class: 'dy-pulse' });",
  "    pulse.style.setProperty('--hs-color', hs.color);",
  "    pulse.style.setProperty('--dy-pulse-min', styles[hs.id].pulseMinRadius);",
  "    pulse.style.setProperty('--dy-pulse-max', styles[hs.id].pulseMaxRadius);",
  "    pulse.style.setProperty('--dy-pulse-speed', styles[hs.id].pulseSpeedMs + 'ms');",
  "    g.appendChild(pulse);",
  "    pulses[hs.id] = pulse;",
  "    hitGroups[hs.id] = g;",
  "    svg.appendChild(g);",
  "  });",
  "",
  "  var connector = s('path', { class: 'dy-connector', pathLength: '1' });",
  "  connector.style.display = 'none';",
  "  svg.appendChild(connector);",
  "",
  "  var groupConnectorPath = s('path', { class: 'dy-group-connector', pathLength: '1' });",
  "  groupConnectorPath.style.display = 'none';",
  "  svg.appendChild(groupConnectorPath);",
  "  var groupConnectorDot = null;",
  "  var groupConnectorRing = null;",
  "",
  "  stageBox.appendChild(img);",
  "  stageBox.appendChild(svg);",
  "  var label = h('div', { class: 'dy-anchor-label dy-font-display', style: 'display:none' });",
  "  stageBox.appendChild(label);",
  "  stage.appendChild(stageBox);",
  "  stageCol.appendChild(stage);",
  "",
  "  var panel = h('aside', { class: 'dy-panel' });",
  "  root.appendChild(stageCol);",
  "  root.appendChild(panel);",
  "",
  "  function select(id) { selectedId = id; render(); }",
  "  function stepBy(dir) {",
  "    if (!sorted.length) return;",
  "    var idx = sorted.findIndex(function (hs) { return hs.id === selectedId; });",
  "    var next = idx === -1 ? 0 : (idx + dir + sorted.length) % sorted.length;",
  "    select(sorted[next].id);",
  "  }",
  "",
  "  function typewriter(container, text, delay) {",
  "    container.textContent = '\\u00A0';",
  "    setTimeout(function () {",
  "      var i = 0;",
  "      var iv = setInterval(function () {",
  "        i++;",
  "        container.textContent = text.slice(0, i);",
  "        if (i >= text.length) clearInterval(iv);",
  "      }, interaction.typewriterSpeedMs);",
  "    }, delay);",
  "  }",
  "",
  "  function buildPanel(hs) {",
  "    panel.innerHTML = '';",
  "    var inner = h('div', { class: 'dy-panel-inner' });",
  "    var headerDot = h('span', { class: 'dy-color-dot', style: 'background:' + hs.color });",
  "    var title = h('h2', {}, [hs.label]);",
  "    var closeBtn = h('button', { class: 'dy-btn' }, ['\\u2715']);",
  "    closeBtn.addEventListener('click', function () { select(null); });",
  "    var header = h('div', { class: 'dy-panel-header' }, [headerDot, title, closeBtn]);",
  "",
  "    var body = h('div', { class: 'dy-panel-body' });",
  "    var group = groupById[hs.groupId];",
  "    if (group) body.appendChild(h('div', { class: 'dy-tools' }, [h('span', {}, [group.label])]));",
  "    if (hs.content.summary) body.appendChild(h('p', { class: 'dy-summary' }, [hs.content.summary]));",
  "",
  "    if (hs.content.steps.length) {",
  "      var stepsWrap = h('div', {}, [h('h3', { class: 'dy-block-title' }, ['De A \\u00e0 Z'])]);",
  "      var list = h('ol', { class: 'dy-step-list', style: 'list-style:none;margin:0;padding-left:22px' });",
  "      hs.content.steps.forEach(function (st, i) {",
  "        var li = h('li', { class: 'dy-step', style: 'animation-delay:' + ((i * interaction.stepStaggerMs) / 1000) + 's' }, [",
  "          h('h4', {}, [st.title]),",
  "          h('p', {}, [st.body]),",
  "        ]);",
  "        list.appendChild(li);",
  "      });",
  "      stepsWrap.appendChild(list);",
  "      body.appendChild(stepsWrap);",
  "    }",
  "",
  "    if (hs.content.example) {",
  "      var exWrap = h('div', {}, [h('h3', { class: 'dy-block-title' }, ['Exemple'])]);",
  "      var exBox = h('div', { class: 'dy-example' });",
  "      exWrap.appendChild(exBox);",
  "      body.appendChild(exWrap);",
  "      typewriter(exBox, hs.content.example, hs.content.steps.length * interaction.stepStaggerMs + 300);",
  "    }",
  "",
  "    if (hs.content.whenToUse) body.appendChild(h('div', {}, [h('h3', { class: 'dy-block-title' }, [\"Quand l'utiliser\"]), h('p', { class: 'dy-summary' }, [hs.content.whenToUse])]));",
  "    if (hs.content.caution) body.appendChild(h('div', {}, [h('h3', { class: 'dy-block-title' }, [\"Point d'attention\"]), h('p', { class: 'dy-summary' }, [hs.content.caution])]));",
  "    if (hs.content.tools.length) {",
  "      var toolsWrap = h('div', {}, [h('h3', { class: 'dy-block-title' }, ['Outils'])]);",
  "      var toolsRow = h('div', { class: 'dy-tools' });",
  "      hs.content.tools.forEach(function (t) { toolsRow.appendChild(h('span', {}, [t])); });",
  "      toolsWrap.appendChild(toolsRow);",
  "      body.appendChild(toolsWrap);",
  "    }",
  "",
  "    var seeAlso = (hs.seeAlso || []).map(function (id) { return byId[id]; }).filter(Boolean);",
  "    if (seeAlso.length) {",
  "      var saWrap = h('div', {}, [h('h3', { class: 'dy-block-title' }, ['Explorer aussi'])]);",
  "      var saRow = h('div', { class: 'dy-tools' });",
  "      seeAlso.forEach(function (other) {",
  "        var dot = h('span', { class: 'dy-legend-dot', style: 'background:' + other.color });",
  "        var btn = h('button', { class: 'dy-see-also' }, [dot, other.label]);",
  "        btn.addEventListener('click', function () { select(other.id); });",
  "        saRow.appendChild(btn);",
  "      });",
  "      saWrap.appendChild(saRow);",
  "      body.appendChild(saWrap);",
  "    }",
  "",
  "    var prevBtn = h('button', { class: 'dy-btn' }, ['\\u2190 Pr\\u00e9c\\u00e9dent']);",
  "    prevBtn.addEventListener('click', function () { stepBy(-1); });",
  "    var nextBtn = h('button', { class: 'dy-btn' }, ['Suivant \\u2192']);",
  "    nextBtn.addEventListener('click', function () { stepBy(1); });",
  "    var replayBtn = h('button', { class: 'dy-btn' }, ['\\u21bb Rejouer']);",
  "    replayBtn.addEventListener('click', function () { buildPanel(hs); });",
  "    var footer = h('div', { class: 'dy-panel-footer' }, [prevBtn, nextBtn, h('span', { class: 'spacer' }), replayBtn]);",
  "",
  "    inner.appendChild(header);",
  "    inner.appendChild(body);",
  "    inner.appendChild(footer);",
  "    panel.appendChild(inner);",
  "  }",
  "",
  "  function updateGroupConnector() {",
  "    if (groupConnectorDot) { groupConnectorDot.remove(); groupConnectorDot = null; }",
  "    if (groupConnectorRing) { groupConnectorRing.remove(); groupConnectorRing = null; }",
  "    if (arrivalSpotlight) { arrivalSpotlight.remove(); arrivalSpotlight = null; }",
  "    var hs = selectedId ? byId[selectedId] : null;",
  "    var conn = hs ? effectiveConnector(hs) : null;",
  "    if (!hs || !conn) {",
  "      groupConnectorPath.classList.remove('drawn');",
  "      groupConnectorPath.style.display = 'none';",
  "      return;",
  "    }",
  "    var d = connectorPathD(hs.anchor, conn.to, conn.curved);",
  "    groupConnectorPath.setAttribute('d', d);",
  "    groupConnectorPath.style.setProperty('--hs-color', hs.color);",
  "    groupConnectorPath.style.display = '';",
  "    groupConnectorPath.classList.remove('drawn');",
  "    if (conn.toShape) {",
  "      arrivalSpotlight = spotlightEl(conn.toShape, hs.color, styles[hs.id]);",
  "      arrivalSpotlight.classList.add('selected');",
  "      svg.appendChild(arrivalSpotlight);",
  "    }",
  "    requestAnimationFrame(function () {",
  "      groupConnectorPath.classList.add('drawn');",
  "      groupConnectorDot = s('circle', { r: 0.7, class: 'dy-group-connector-dot' });",
  "      groupConnectorDot.style.setProperty('--hs-color', hs.color);",
  "      var motion = s('animateMotion', { dur: interaction.connectorDotSpeedMs + 'ms', repeatCount: 'indefinite', path: d });",
  "      groupConnectorDot.appendChild(motion);",
  "      svg.appendChild(groupConnectorDot);",
  "      groupConnectorRing = s('circle', { cx: conn.to.x, cy: conn.to.y, class: 'dy-ring' });",
  "      groupConnectorRing.style.setProperty('--hs-color', hs.color);",
  "      groupConnectorRing.style.setProperty('animation-duration', interaction.ringSpeedMs + 'ms');",
  "      svg.appendChild(groupConnectorRing);",
  "    });",
  "  }",
  "",
  "  function render() {",
  "    project.hotspots.forEach(function (hs) {",
  "      var el = spotlights[hs.id];",
  "      el.classList.remove('hovered', 'selected', 'dimmed');",
  "      if (hs.id === selectedId) el.classList.add('selected');",
  "      else if (selectedId) el.classList.add('dimmed');",
  "      else if (hs.id === hoverId) el.classList.add('hovered');",
  "",
  "      var pulse = pulses[hs.id];",
  "      var showPulse = styles[hs.id].pulseEnabled && !selectedId && hs.id !== hoverId;",
  "      pulse.style.display = showPulse ? '' : 'none';",
  "    });",
  "    if (!selectedId && hoverId && byId[hoverId]) {",
  "      var hh = byId[hoverId];",
  "      label.style.display = '';",
  "      label.style.left = hh.anchor.x + '%';",
  "      label.style.top = hh.anchor.y + '%';",
  "      label.textContent = hh.label;",
  "    } else {",
  "      label.style.display = 'none';",
  "    }",
  "    var selectionChanged = selectedId !== renderedPanelId;",
  "    if (selectedId) {",
  "      var hs = byId[selectedId];",
  "      panel.classList.add('open');",
  "      if (selectionChanged) {",
  "        if (interaction.showPanelConnector) {",
  "          var targetX = project.theme.panelSide === 'left' ? 0 : 100;",
  "          connector.setAttribute('d', connectorPathD(hs.anchor, { x: targetX, y: hs.anchor.y }, interaction.panelConnectorCurved));",
  "          connector.style.display = '';",
  "          connector.classList.remove('drawn');",
  "          requestAnimationFrame(function () { connector.classList.add('drawn'); });",
  "        } else {",
  "          connector.style.display = 'none';",
  "        }",
  "        buildPanel(hs);",
  "        updateGroupConnector();",
  "      }",
  "    } else if (selectionChanged) {",
  "      connector.classList.remove('drawn');",
  "      connector.style.display = 'none';",
  "      panel.classList.remove('open');",
  "      panel.innerHTML = '';",
  "      updateGroupConnector();",
  "    }",
  "    renderedPanelId = selectedId;",
  "  }",
  "",
  "  document.addEventListener('keydown', function (e) {",
  "    if (!selectedId) return;",
  "    if (e.key === 'Escape') select(null);",
  "    if (e.key === 'ArrowRight') stepBy(1);",
  "    if (e.key === 'ArrowLeft') stepBy(-1);",
  "  });",
  "",
  "  render();",
  "})();",
].join("\n");
